### ISSUE TITLE
Solo mining memorycoin

### ISSUE THREAD

**Issue by sburina** [reorder/momentum-getwork#2]
Hi!

Is it possible to make this miner work with the newest release of memorycoind, in solo mining mode?
I've just tried it, it connects to the daemon and submits some work occasionally, but always with the same result:

Sun Dec 28 11:38:12 2014 Worker 0 hpm 753.095504 wpm 215.225887 queue 1/0 --> Upstream RPC result: False

Thank you!

**Comment by reorder** [comment]
This is a miner for PTS (protoshares), not for memorycoin. PoW algos are different. Now that PTS has switched to DPOS it is only useable for other Momentum coins (Noirbits?)

**Comment by sburina** [comment]
Thank you for your swift reply, you're so kind. :)
