### ISSUE TITLE
Not working with bitcredits for some reason

### ISSUE THREAD

**Issue by blopper** [reorder/momentum-getwork#3]
Hello, as this is the only open source solo miner for the momentum pow and just a few coins use it can you perhaps look into why it's unable to submit valid blocks? Whenever a block is found I get "RPC results: false" If I copy the hex string and paste it after submitblock via rpc manually I get "Block decode failed"

**Comment by reorder** [comment]
getwork call only accepts block header, so it is not accepted as it is not the full block.

Perhaps there is something in coin daemon debug.log when getwork submission returns false?

**Comment by blopper** [comment]
I kept tailing the debug.log while it was mining it, and couldn't notice anything. Any tips how to make it more verbose when it's finding a block and tries to submit it?

**Comment by reorder** [comment]
Check/Accept/ConnectBlock methods are usually quite verbose (in recent bitcoin core versions and their forks). Where do I find the coin wallet source?

**Comment by blopper** [comment]
The source is here https://github.com/bitcreditscc/bicreditsnew

$ grep -i Check ../../.bitcredit/debug.log
2015-01-13 13:15:44 Checking all blk files are present...
2015-01-13 13:17:47 Checking all blk files are present...
2015-01-13 13:19:48 Checking all blk files are present...
2015-01-13 13:20:04 Checking all blk files are present...
2015-01-13 13:20:25 Checking all blk files are present...
2015-01-13 16:29:51 Checking all blk files are present...
$ grep -i Accept ../../.bitcredit/debug.log
$ grep -i ConnectBlock  ../../.bitcredit/debug.log

**Comment by reorder** [comment]
Ok now I remember, the miner was initially made for 'ptspool' pool that had a hardcoded target of 1. Thus it submits everything it finds, even if solution is above the target. So it is likely working correclty and if it finds a block it will get submitted.

**Comment by blopper** [comment]
So you reckon I haven't yet been lucky enough to find a block?

**Comment by reorder** [comment]
Likely so.

**Comment by blopper** [comment]
Ok, thank you very much for your time.

**Comment by blopper** [comment]
I ran it with 6000hpm for about 3 hours now and I keep getting RPC result: false or none with nothing coming up in the debug.log, with the current diff of 0.00000033 I should have found quite a few blocks based on the network hashrate and block time.

**Comment by blopper** [comment]
Any hope to take a closer look at bitcredits?

**Comment by reorder** [comment]
If you can add some debug prints to getwork handler of the coin daemon and its CheckBlock method to identify what is causing the issue, I could probably come up with a fix. At a glance I could not find how it is different from PTS.

**Comment by blopper** [comment]
I removed a return false statement one that checked target and this is what I got when it submitted a block in the debug.log file

015-01-15 21:48:15 CBlock(hash=7a16df66736fd8ec211a4058c8124904963928539308e0e53e0ed07bfa41badf, ver=2, hashPrevBlock=00027d2394a414918d68bdb3cdf74e9612a94928eb415d705288d19ca0389781, hashMerkleRoot=d429925ed6c0a96328a230d102f704750b020c70b2a5b911c68e81e56b5285ce, nTime=1421358493, nBits=1f408910, nNonce=0, vtx=1)
  CTransaction(hash=d429925ed6, ver=1, vin.size=1, vout.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 02362d020001062f503253482f)
    CTxOut(nValue=50.00000000, scriptPubKey=1)

  vMerkleTree:  d429925ed6c0a96328a230d102f704750b020c70b2a5b911c68e81e56b5285ce

2015-01-15 21:48:15 generated 50.00
2015-01-15 21:48:15 ERROR: CheckProofOfWork() : hash doesn't match nBits
2015-01-15 21:48:15 ERROR: CheckBlockHeader() : proof of work failed
2015-01-15 21:48:15 ERROR: ProcessNewBlock : CheckBlock FAILED
2015-01-15 21:48:15 ERROR: BitcreditMiner : ProcessNewBlock, block not accepted
Hope it helps.

I removed this check to make it log;

https://github.com/bitcreditscc/bicreditsnew/blob/master/src/miner.cpp#L450-L451

Otherwise it just returns false and the miner just gets false as response.

**Comment by reorder** [comment]
Please uncomment line 195 in miner.py and post the data it tries to submit.

**Comment by blopper** [comment]
Submitting 02000000ecfa773e86ed02debd23a6baea109cd5f96db3922f1c32493ddf8dd6e3ce0000c24bd9b50b51c7aeaf5a2fd75d84cc0b368ec2466a9da9d3ddefd62a582f1f3e633cb8543304661e000000008bcd3103af05b402

**Comment by blopper** [comment]
Submitting 02000000ecfa773e86ed02debd23a6baea109cd5f96db3922f1c32493ddf8dd6e3ce0000694bd1bd39b5d3de94f3ddb9a6337602b9060332f75ae641cefedf12ab7eebfe4f44b8543304661e00000000be11f400f15afd01

2015-01-15 22:50:57 CBlock(hash=67c14b957185478389ffd72f3715bebc2158322510426cebd8e1a676c7b3aafb, ver=2, hashPrevBlock=0000cee3d68ddf3d49321c2f92b36df9d59c10eabaa623bdde02ed863e77faec, hashMerkleRoot=771ff0c7377b9244e2ed1dd1a5ea664144ea992785e729d8b7a86e8663bffbdd, nTime=1421362255, nBits=1e660433, nNonce=0, vtx=1)
  CTransaction(hash=771ff0c737, ver=1, vin.size=1, vout.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 023c2d021a27062f503253482f)
    CTxOut(nValue=50.00000000, scriptPubKey=1)

  vMerkleTree:  771ff0c7377b9244e2ed1dd1a5ea664144ea992785e729d8b7a86e8663bffbdd

2015-01-15 22:50:57 generated 50.00
2015-01-15 22:50:57 ERROR: CheckProofOfWork() : hash doesn't match nBits
2015-01-15 22:50:57 ERROR: CheckBlockHeader() : proof of work failed
2015-01-15 22:50:57 ERROR: ProcessNewBlock : CheckBlock FAILED
2015-01-15 22:50:57 ERROR: BitcreditMiner : ProcessNewBlock, block not accepted

**Comment by reorder** [comment]
So it says block hash is 67c14b957185478389ffd72f3715bebc2158322510426cebd8e1a676c7b3aafb.

But, if I recalculate, I get this:

```
>>>hashlib.sha256(hashlib.sha256('02000000ecfa773e86ed02debd23a6baea109cd5f96db3922f1c32493ddf8dd6e3ce0000694bd1bd39b5d3de94f3ddb9a6337602b9060332f75ae641cefedf12ab7eebfe4f44b8543304661e00000000be11f400f15afd01'.decode('hex')).digest()).hexdigest()
'26a29fcbf03f90f91be1371e9f29f111730317ece2e424fea17f554468520000'
```

So what does this coin have different?

By the way, I have rechecked and getwork target is actually honored by the miner (as it is in this sample)

**Comment by blopper** [comment]
Beats me man, I'm cluless. Perhaps nNonce is 1 or something? Any pointers what should I been looking for? diff some sources between the two etc?

**Comment by reorder** [comment]
Ok apparently getwork is broken in the coin due to this line commented out: https://github.com/bitcreditscc/bicreditsnew/blob/master/src/rpcmining.cpp#L413

Next line modifies merkle root in new block header so it is no more equal to the block that was mined.

**Comment by blopper** [comment]
I noticed that too, I've found a block with it uncommented but no luck, it appears getwork is deliberately broken?

**Comment by reorder** [comment]
Well, no idea, you are better off asking the coin dev.

**Comment by blopper** [comment]
Yep, dev admitted it's broken, just wish I knew before I started bothering you about it. He offered 0.5btc bounty for a fix. Thanks a lot for putting up with me man, much appreciated.

**Comment by reorder** [comment]
He is also creating the new block with a dummy coinbase (anyone could spend it if not for CScript validation rules): https://github.com/bitcreditscc/bicreditsnew/blob/master/src/rpcmining.cpp#L351

Well, if you feel like fixing that, you could try replacing that CScript with result of GetScriptForDestination(your_key) and uncommenting the line that fixes up the coinbase in submitted block. I am closing this now as it is not a miner bug.
